### ISSUE TITLE
使用2023-06最新版本的docker compose，遇到异常，无法抓取全文

### ISSUE THREAD

**Issue by lmmsoft** [WangQiru/mercury_fulltext#28]
* ## _What_ is the issue?

使用2023-06最新版本的docker compose，遇到异常，无法抓取全文

* ## _What_ is your setup? (PHP version, database used, etc.)

PHP Version 8.1.20 (in docker)+ Azure Database for postgres(in cloud)

* ## _Are_ there any error logs?
```
plugins.local/mercury_fulltext/init.php:279

Uncaught TypeError: property_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /var/www/plugins.local/mercury_fulltext/init.php:279
Stack trace:
#0 /var/www/plugins.local/mercury_fulltext/init.php(279): property_exists()
#1 /var/www/classes/pluginhandler.php(15): mercury_fulltext->extract()
#2 /var/www/backend.php(169): PluginHandler->catchall()
#3 {main}
  thrown

Request URI: /backend.php
User agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36
```

* ## _How_ can the issue be replicated?

* ## Other Comments

**Comment by lmmsoft** [comment]
通过降级ttrss解决了
参考解决方案：https://lmmsoft.github.io/downgrade_ttrss/
